let {
  SERVER,
  LOGIN_API,
  HOST,
  NODE_ENV,
  // PG数据库信息
  PG_USERNAME,
  PG_PASSWORD,
  PG_DATABASE,
  PG_PORT,
  PG_HOST,
  // OSS服务
  OSS_REGION,
  OSS_ACCESS_KEY_ID,
  OSS_ACCESS_KEY_SECRET,
  OSS_BUCKET,
  OSS_DOMAIN_INTERNAL,
  OSS_DOMAIN,
  OSS_CDN,
  OSS_BUCKET_PREFIX,
  // 发送短信服务
  SMS_URL,
  SMS_USER_ID,
  SMS_API_KEY,
  SMS_PROVIDER,
  SMS_MODE,
  SMS_SIGNATURE,
  SMS_TEMPLATE_ID,
  // 管理后台密码
  ADMIN_USERNAME,
  ADMIN_PASSWORD,
} = process.env;

console.log(`[Avatar log]:
    系统:环境变量初始化成功, = = => 
    SERVER:${SERVER},
    LOGIN_API:${LOGIN_API},
    HOST:${HOST},
    NODE_ENV:${NODE_ENV}\n

    PG:环境变量初始化成功, = = => 
    PG_HOST:${PG_HOST},
    PG_PORT:${PG_PORT},
    PG_DATABASE:${PG_DATABASE},
    PG_USERNAME:${PG_USERNAME},
    PG_PASSWORD:${PG_PASSWORD}\n

    OSS:环境变量初始化成功, = = => 
    OSS_REGION:${OSS_REGION}, 
    OSS_ACCESS_KEY_ID:${OSS_ACCESS_KEY_ID},
    OSS_ACCESS_KEY_SECRET:${OSS_ACCESS_KEY_SECRET},
    OSS_BUCKET:${OSS_BUCKET}\n

    短信:环境变量初始化成功, = = => 
    SMS_URL:${SMS_URL}, 
    SMS_USER_ID:${SMS_USER_ID},
    SMS_API_KEY:${SMS_API_KEY},
    SMS_PROVIDER:${SMS_PROVIDER},
    SMS_MODE:${SMS_MODE},
    SMS_SIGNATURE:${SMS_SIGNATURE},
    SMS_TEMPLATE_ID:${SMS_TEMPLATE_ID}\n

    管理后台:环境变量初始化成功, = = => 
    ADMIN_USERNAME:${ADMIN_USERNAME}, 
    ADMIN_PASSWORD:${ADMIN_PASSWORD},
  `);
export {
  SERVER,
  LOGIN_API,
  HOST,
  NODE_ENV,
  PG_USERNAME,
  PG_PASSWORD,
  PG_DATABASE,
  PG_PORT,
  PG_HOST,
  OSS_REGION,
  OSS_ACCESS_KEY_ID,
  OSS_ACCESS_KEY_SECRET,
  OSS_BUCKET,
  OSS_DOMAIN_INTERNAL,
  OSS_DOMAIN,
  OSS_CDN,
  OSS_BUCKET_PREFIX,
  SMS_URL,
  SMS_USER_ID,
  SMS_API_KEY,
  SMS_PROVIDER,
  SMS_MODE,
  SMS_SIGNATURE,
  SMS_TEMPLATE_ID,
  ADMIN_USERNAME,
  ADMIN_PASSWORD,
};
